version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      - "MYSQL_ROOT_PASSWORD=rooty"
      - "MYSQL_DATABASE=awesomedb"
    ports:
      - "3306:3306"
    volumes:
      - "db:/var/lib/mysql"

volumes:
  db: